artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://www.kaggle.com/api/v1/datasets/download/ra4u12/bookrecommendation
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data